Fixing docker action to respect DOCKER_LATEST_BRANCH
cresta/magehelper pull request #12
Opened 2021-07-06 18:31 UTC by scallister

Created in response to:
https://github.com/cresta/magehelper/pull/11/files/547ba72bcc3e3f77b59e2e35dc4d45caa8cc8b89#r664730664

@cep21 I think this will respect `DOCKER_LATEST_BRANCH` better.

2021-07-09 23:43 UTC, scallister commented
@cep21 I think this PR slipped through the cracks. Did you still want this?

It's failing on a naked return, I'm surprised we're checking for that 🤔 . Naked returns (with named variables) have a valid place in Go code. I think I see where that is configured in `magehelper`, any issues with me removing the check for naked returns?

2021-07-10 17:05 UTC, cep21 requested changes

2021-07-10 17:05 UTC, cep21 commented on docker/docker.go
>  func (d *Docker) latestBranch() (latestBranch string) {
Why is this a named return?  Can we revert this to just returning string?

2021-07-20 23:04 UTC, scallister commented on docker/docker.go
>  func (d *Docker) latestBranch() (latestBranch string) {
It got switched here:
https://github.com/cresta/magehelper/commit/5e4d99f71cb539a5a09bed0d8e23da981189ba31#diff-3b425d7dadd18dc6d2fadc2bc169afae1f7bbc8f757a66d2837e9e78fb792c90R151-R182

Reasoning for switching to a named return was because there were 6 returns that should all return the same variable. It felt better to declare the promise of `latestBranch` at the top of the function since that is what is always returned.

Another note on that code. We did not add error handling to this function because while @jmatt and I were patching this function to make it compatible with `main` and `master`, we were not able to get `magehelper` to run locally, and we did not want to introduce an additional failure since in the case of a failure we could always revert back to the original behavior of providing the `master` branch.

2021-07-20 23:42 UTC, cep21 commented on docker/docker.go
>  func (d *Docker) latestBranch() (latestBranch string) {
> Reasoning for switching to a named return was because there were 6 returns that should all return the same variable. 

That's fine and common in go code.

2021-07-21 00:58 UTC, scallister commented on docker/docker.go
>  func (d *Docker) latestBranch() (latestBranch string) {
Updated PR

2021-07-21 01:00 UTC, cep21 approved these changes

2021-07-21 01:00 UTC, cep21 commented on docker/docker.go
> +	oldDefaultBranch := "master"
May as well make oldDefaultBranch a `const`

2021-07-21 01:10 UTC, scallister commented on docker/docker.go
> +	oldDefaultBranch := "master"
Done

2021-07-21 01:12 UTC, merged